spring.application.name=m3bookshelfpro

spring.datasource.url=jdbc:mysql://z37udk8g6jiaqcbx.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/cnwahati2n2gu7dk
spring.datasource.username=noq7p1hbcoygwdfr
spring.datasource.password=dt2sqpcef6cnv0em
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false
