package com.m3bookshelfpro.model;

import jakarta.persistence.*;
import lombok.Data;

/**
 * Book entity representing a single book in the BookShelf Pro catalog.
 *
 * <p>This class maps to the {@code books} table in the MySQL database.
 * Each book belongs to a {@link Category} via a many-to-one relationship.
 * Lombok's {@code @Data} annotation automatically generates getters,
 * setters, equals, hashCode, and toString methods.</p>
 *
 * @author Jacob Israel
 * @author Peyton Wolf
 * @version 4.0
 * @see Category
 */
@Data
@Entity
@Table(name = "books")
public class Book {

    /**
     * Unique identifier for the book, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The title of the book.
     */
    private String title;

    /**
     * The name of the book's author.
     */
    private String author;

    /**
     * The genre of the book (e.g., Fiction, Non-Fiction, Science).
     */
    private String genre;

    /**
     * The International Standard Book Number (ISBN) of the book.
     */
    private String isbn;

    /**
     * The retail price of the book in USD.
     */
    private Double price;

    /**
     * The current stock quantity available in the catalog.
     */
    private Integer quantity;

    /**
     * The category this book belongs to.
     * Mapped via a foreign key {@code category_id} in the books table.
     */
    @ManyToOne
    @JoinColumn(name = "category_id")
    private Category category;
    
    public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
}
