package com.m3bookshelfpro.model;

import jakarta.persistence.*;
import lombok.Data;

/**
 * Category entity representing a book classification in the BookShelf Pro catalog.
 *
 * <p>This class maps to the {@code categories} table in the MySQL database.
 * Each category can be associated with multiple {@link Book} records.
 * Lombok's {@code @Data} annotation automatically generates getters,
 * setters, equals, hashCode, and toString methods.</p>
 *
 * @author Jacob Israel
 * @author Peyton Wolf
 * @version 4.0
 * @see Book
 */
@Data
@Entity
@Table(name = "categories")
public class Category {

    /**
     * Unique identifier for the category, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The display name of the category (e.g., Fiction, Science, History).
     */
    private String name;

    /**
     * A brief description of what books belong in this category.
     */
    private String description;
    
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
}
