- name: Deploy to Heroku
  run: |
      git config --global user.email "${{ secrets.HEROKU_EMAIL }}"
      git config --global user.name "github-actions"

      git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

      git push https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git HEAD:main --force
